version: '3.2'

services:
  app:
    build:
      context: .
    ports:
      - "80:8000"
    volumes:
      - .:/project
      - ~/.composer:/root/.composer
    links:
      - "db"
    working_dir: /project
    command: php -S 0.0.0.0:8000 -t public public/index.php

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopify_skeleton
