# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    CodeCloud\Bundle\ShopifyBundle\Model\ShopifyStoreManagerInterface: '@App\Service\StoreManager'

code_cloud_shopify:
    oauth:
        api_key: '%env(resolve:SHOPIFY_API_KEY)%'
        shared_secret: '%env(resolve:SHOPIFY_SHARED_SECRET)%'
        scope: ""
        redirect_route: "admin_dashboard"
    api_version: "2021-01"
    webhooks:
        - app/uninstalled
